api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'leads', views.LeadsViewSet, basename="leads")



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='app'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('leads/', views.leads, name='leads'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

bringme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('api/', include('api.urls'))
]

app/templates/login/login.html
{% extends 'base/base.html' %} {% load static %}
<!--  -->
{% block content %}

<div class="login-page">

    <div class="form">
        <form action="{% url 'app:login' %}" method="POST" class="login-form">
            <img class="pb-2" src="{% static 'imgs/logo.png' %}" width="200px" alt="">
            <!--  -->
            {% csrf_token %}
            <input type="text" placeholder="Usuário" name="username" />
            <input type="password" placeholder="Senha" name="password" />
            <button>login</button>
            <!-- <input type="submit" value="LOGIN"> -->
            <p class="message ">Sem Registro? <a href="# ">Solicitar conta</a></p>
        </form>
    </div>
</div>


{% endblock %}