api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'leads', views.LeadsViewSet, basename="leads")



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='app'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('leads/', views.leads, name='leads'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

bringme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('api/', include('api.urls'))
]

app/templates/navbar/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color:rgba(0,0,0,.05);box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.1), 0 12px 12px 0 rgba(0, 0, 0, 0.10);">
    <a class="navbar-brand" href="{% url 'app:homepage' %}"><img class="pb-2" src="{% static 'imgs/logo.png' %}" width="50px" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'app:homepage' %}"><i class="fas fa-search"></i>  Procurar <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'app:leads' %}"><i class="fas fa-users"></i>  Seus Leads</a>
            </li>
            <div style="position: absolute; right: 0;">
                <li class="nav-item active ">
                    <a class="nav-link" href="{% url 'app:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </li>
            </div>


    </div>
</nav>